from abc import ABC, abstractmethod
class DroneInterface(ABC):
 @abstractmethod
 async def connect(self): ...
 @abstractmethod
 async def disconnect(self): ...
 @abstractmethod
 async def get_status(self): ...
 @abstractmethod
 async def get_telemetry(self): ...
 @abstractmethod
 async def command(self, name, payload=None): ...
 @abstractmethod
 async def upload_mission(self, items): ...
 @abstractmethod
 async def download_mission(self): ...
 @abstractmethod
 async def get_parameters(self): ...
 @abstractmethod
 async def set_parameter(self, name, value): ...
